workflows:
  android-workflow:
    name: VibePlay Android Build
    max_build_duration: 120
    instance_type: mac_mini_m1
    environment:
      node: 20
      java: 17
      android_signing:
        - keystore_reference
      vars:
        PACKAGE_NAME: "com.vibeplay.app"
    scripts:
      - name: Install dependencies
        script: |
          npm install

      - name: Build web app
        script: |
          npm run build

      - name: Sync Capacitor
        script: |
          npx cap sync android

      - name: Set up local.properties
        script: |
          echo "sdk.dir=$ANDROID_SDK_ROOT" > "$CM_BUILD_DIR/android/local.properties"

      - name: Build Android Debug APK
        script: |
          cd android
          chmod +x gradlew
          ./gradlew assembleDebug

    artifacts:
      - android/app/build/outputs/**/*.apk
      - android/app/build/outputs/**/mapping.txt

    publishing:
      email:
        recipients:
          - user@example.com
        notify:
          success: true
          failure: true
